apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

configMapGenerator:
- behavior: merge
  literals:
  - database_host=prod-db.example.com
  name: app-config

labels:
- includeSelectors: true
  pairs:
    app: web-app